inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  NewCops: enable
  TargetRubyVersion: "3.0"
  TargetRailsVersion: "6.1"

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: 'indented_relative_to_receiver'

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/ExampleWithoutDescription:
  EnforcedStyle: single_line_only

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/FilePath:
  Exclude:
    - spec/**/scope/*_spec.rb

RSpec/PredicateMatcher:
  Enabled: false

Style/GuardClause:
  Enabled: false

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/SymbolArray:
  EnforcedStyle: brackets
