require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: "3.2"
  TargetRailsVersion: "6.1"

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: 'indented_relative_to_receiver'

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/ExampleWithoutDescription:
  EnforcedStyle: single_line_only

RSpec/ExpectChange:
  EnforcedStyle: block

Rails/FilePath:
  Exclude:
    - spec/**/scope/*_spec.rb

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/PredicateMatcher:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

RSpec/SpecFilePathFormat:
  Enabled: false

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/SymbolArray:
  EnforcedStyle: brackets
