# frozen_string_literal: true

class AddAutoGeneratedPasswordFlag < ActiveRecord::Migration[6.1]
  def change
    add_column :users, :auto_gen_password, :boolean, default: false, null: false
  end
end
